### ISSUE TITLE
0. 자기소개!

### ISSUE THREAD

**Issue by Myeongchan-Kim** [Paul-Kim/Mobile_Doctor#1]
간단한 자기소개 댓글로 달아주세요!
제가 누가 누군지 헷갈려서...

모두 달면 close하겠습니다.

**Comment by Myeongchan-Kim** [comment]
이 깃헙 페이지는 임시 페이지 이며 우리 서비스에 큰 영향을 끼치지 않습니다. 
따라서 맘껏 쓰셔도 됩니다.

**Comment by hangumin** [comment]
포항공대 생명과학과 다니고 있는 15학번 3학년 한구민이라고 합니다! 잘부탁드립니다~

**Comment by Kimkangmin-oscar** [comment]
카이스트 산업 및 시스템 공학과 14학번 4학년 김강민 입니다.
감사합니다!

**Comment by Myeongchan-Kim** [comment]
반갑습니다 ㅎㅎ 거기랑 여기랑 시차가 좀나서..;; 제가 오전이랑 저녁밖에 확인을 못하네요. 궁금한것 있으면 카톡으로도 언제든지 물어보시고! 이슈관련해서는 여기에 댓글로 물어보셔도 됩니다.

**Comment by GY-jung** [comment]
카이스트 경영대학원 석사 17 정기영입니다.

**Comment by GY-jung** [comment]
깉헙 쓰기가 너무 생소하네요 많이 가르쳐주세요 감사합니다

**Comment by Myeongchan-Kim** [comment]
반갑습니다!
